<?php

class options 
{
    function __construct() {
        if( function_exists('acf_add_options_page') ) {
            global $current_user;
            $username = $current_user->user_login;

            $this->enable_theme_setting();
            $this->add_theme_options_field();
            $this->add_theme_slider_field();
            $this->add_theme_category_field();
            $this->add_theme_recruitment_field();
            if ( class_exists( 'WooCommerce' ) ) {
                $this->add_theme_product_field();
            }
            $this->add_theme_contact_field();
            
            if( $username == 'uniadmin' ) {
                $this->add_theme_admin_field();
            }
        }
    }

    public function enable_theme_setting() { 
        
        if( function_exists('acf_add_options_page') ) {
            global $current_user;
            $username = $current_user->user_login;
	
            acf_add_options_page(array(
                'page_title' 	=> esc_html__( 'Theme Options', 'shtheme' ),
                'menu_title'	=> esc_html__( 'Theme Options', 'shtheme' ),
                'menu_slug' 	=> 'theme-options',
                'capability'	=> 'edit_posts',
                'redirect'		=> false
            ));

            acf_add_options_sub_page(array(
                'page_title' 	=> esc_html__( 'Theme Block Settings', 'shtheme' ),
                'menu_title'	=> esc_html__( 'Block', 'shtheme' ),
                'menu_slug' 	=> 'theme-block-settings',
                'parent_slug'	=> 'theme-options',
            ));
            acf_add_options_sub_page(array(
                'page_title' 	=> esc_html__( 'Theme Slider Settings', 'shtheme' ),
                'menu_title'	=> esc_html__( 'Slider', 'shtheme' ),
                'menu_slug' 	=> 'theme-slider-settings',
                'parent_slug'	=> 'theme-options',
            ));
            acf_add_options_sub_page(array(
                'page_title' 	=> esc_html__( 'Theme Category Settings', 'shtheme' ),
                'menu_title'	=> esc_html__( 'Category', 'shtheme' ),
                'menu_slug' 	=> 'theme-category-settings',
                'parent_slug'	=> 'theme-options',
            ));
            acf_add_options_sub_page(array(
                'page_title' 	=> esc_html__( 'Theme Recruitment Settings', 'shtheme' ),
                'menu_title'	=> esc_html__( 'Recruitment', 'shtheme' ),
                'menu_slug' 	=> 'theme-recruitment-settings',
                'parent_slug'	=> 'theme-options',
            ));

            if ( class_exists( 'WooCommerce' ) ) {
                acf_add_options_sub_page(array(
                    'page_title' 	=> esc_html__( 'Product Settings', 'shtheme' ),
                    'menu_title'	=> esc_html__( 'Product', 'shtheme' ),
                    'menu_slug' 	=> 'theme-product-settings',
                    'parent_slug'	=> 'theme-options',
                ));
            }

            acf_add_options_sub_page(array(
                'page_title' 	=> 'Theme Contact Settings',
                'menu_title'	=> esc_html__( 'Contact', 'shtheme' ),
                'menu_slug' 	=> 'theme-contact-settings',
                'parent_slug'	=> 'theme-options',
            ));
            if( $username == 'uniadmin' ) {
                acf_add_options_sub_page(array(
                    'page_title' 	=> 'Admin',
                    'menu_title'	=> 'Admin',
                    'menu_slug' 	=> 'theme-admin',
                    'parent_slug'	=> 'theme-options',
                ));
            }
            
        }
    }
    public function add_theme_options_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'theme_option_1',
                'title' => esc_html__( 'Theme Options', 'shtheme' ),
                'fields' => array(
                    /****************** 
                    * Setting
                    ******************/
                    array(
                        'key' => 'theme_option_2',
                        'label' => esc_html__( 'Settings', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'theme_option_3',
                        'label' => esc_html__( 'Logo', 'shtheme' ),
                        'name' => 'logo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'theme_option_4',
                        'label' => esc_html__( 'Favicon', 'shtheme' ),
                        'name' => 'favicon',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'theme_option_5',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'opt-layout',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'theme_option_6',
                        'label' => esc_html__( 'Enable Page Title Bar', 'shtheme' ),
                        'name' => 'display-pagetitlebar',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    
                    /* ***************** 
                    * Color 
                    ***************** */
                    array(
                        'key' => 'theme_option_7',
                        'label' => esc_html__( 'Color', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'theme_option_8',
                        'label' => esc_html__( 'Primary Color', 'shtheme' ),
                        'name' => 'primary_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#91c544',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'theme_option_9',
                        'label' => esc_html__( 'Secondary Color', 'shtheme' ),
                        'name' => 'secondary_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#000000',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'theme_option_10',
                        'label' => esc_html__( 'Text Color', 'shtheme' ),
                        'name' => 'text_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#222222',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    /****************** 
                    * Google API 
                    ******************/
                    array(
                        'key' => 'theme_option_11',
                        'label' => esc_html__( 'Google API', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'theme_option_12',
                        'label' => esc_html__( 'Google API', 'shtheme' ),
                        'name' => 'google_api',
                        'type' => 'password',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    /****************** 
                    * Header 
                    ******************/
                    array(
                        'key' => 'theme_option_13',
                        'label' => esc_html__( 'Header', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'theme_option_14',
                        'label' => esc_html__( 'Enable Top Header Widget', 'shtheme' ),
                        'name' => 'display-topheader-widget',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'theme_option_15',
                        'label' => esc_html__( 'Header Layout', 'shtheme' ),
                        'name' => 'opt-layout-header',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'Layout 1',
                            2 => 'Layout 2',
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    /****************** 
                    * Footer 
                    ******************/
                    array(
                        'key' => 'theme_option_16',
                        'label' => esc_html__( 'Footer', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'theme_option_17',
                        'label' => esc_html__( 'Enter number column footer', 'shtheme' ),
                        'name' => 'opt-number-footer',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 3,
                        'min' => 1,
                        'max' => 6,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'theme_option_18',
                        'label' => esc_html__( 'Copyright', 'shtheme' ),
                        'name' => 'footer-copyright',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-options',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_slider_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'slider_1',
                'title' => esc_html__( 'Slider Settings', 'shtheme' ),
                'fields' => array(
                    array(
                        'key' => 'slider_2',
                        'label' => esc_html__( 'Enable gallery slider', 'shtheme' ),
                        'name' => 'btn-slide-switch',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'slider_3',
                        'label' => esc_html__( 'Gallery Slide', 'shtheme' ),
                        'name' => 'setting-slider',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => esc_html__('Add new', 'shtheme' ),
                        'sub_fields' => array(
                            array(
                                'key' => 'slider_4',
                                'label' => esc_html__( 'Image', 'shtheme' ),
                                'name' => 'slide_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'slider_5',
                                'label' => esc_html__( 'Text Effect', 'shtheme' ),
                                'name' => 'slide_title',
                                'type' => 'image',
                            ),
                            // array(
                            //     'key' => 'slider_6',
                            //     'label' => esc_html__( 'Description', 'shtheme' ),
                            //     'name' => 'slide_description',
                            //     'type' => 'textarea',
                            //     'instructions' => '',
                            //     'required' => 0,
                            //     'conditional_logic' => 0,
                            //     'wrapper' => array(
                            //         'width' => '',
                            //         'class' => '',
                            //         'id' => '',
                            //     ),
                            //     'default_value' => '',
                            //     'placeholder' => '',
                            //     'maxlength' => '',
                            //     'rows' => '',
                            //     'new_lines' => '',
                            // ),
                            array(
                                'key' => 'slider_7',
                                'label' => esc_html__( 'Permalink', 'shtheme' ),
                                'name' => 'slide_url',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-slider-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_category_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'blogpost_1',
                'title' => esc_html__( 'Category Settings', 'shtheme' ),
                'fields' => array(
                    /****************** 
                    * Category 
                    ******************/
                    array(
                        'key' => 'blogpost_2',
                        'label' => esc_html__( 'Category post', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'blogpost_3',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'blogpost-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'blogpost_4',
                        'label' => esc_html__( 'Display hierarchy category', 'shtheme' ),
                        'name' => 'blogpost-hierarchy',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_5',
                        'label' => esc_html__( 'Choose category style', 'shtheme' ),
                        'name' => 'blogpost-style',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => esc_html__( 'Pagination', 'shtheme' ),
                            2 => esc_html__( 'Load more', 'shtheme' ),
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'blogpost_6',
                        'label' => esc_html__( 'Category layout', 'shtheme' ),
                        'name' => 'blogpost-layout',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'Style 1',
                            2 => 'Style 2',
                            3 => 'Style 3',
                            4 => 'Style 4',
                            5 => 'Style 5',
                        ),
                        'allow_null' => 0,
                        'default_value' => '1',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'blogpost_7',
                        'label' => esc_html__( 'Enter number post', 'shtheme' ),
                        'name' => 'blogpost-number-post',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 30,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'blogpost_8',
                        'label' => esc_html__( 'Enable Posts Thumb', 'shtheme' ),
                        'name' => 'blogpost-thumb',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_9',
                        'label' => esc_html__( 'Enable Posts Category', 'shtheme' ),
                        'name' => 'blogpost-category',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_10',
                        'label' => esc_html__( 'Enable Posts Meta', 'shtheme' ),
                        'name' => 'blogpost-meta',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_11',
                        'label' => esc_html__( 'Enable Posts Description', 'shtheme' ),
                        'name' => 'blogpost-desc',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_12',
                        'label' => esc_html__( 'Enable Posts Permalink', 'shtheme' ),
                        'name' => 'blogpost-link',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    /****************** 
                    * Single Post 
                    ******************/ 
                    array(
                        'key' => 'blogpost_13',
                        'label' => esc_html__( 'Single post', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'blogpost_14',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'blogpost-single-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'blogpost_15',
                        'label' => esc_html__( 'Display time and view post', 'shtheme' ),
                        'name' => 'blogpost-single-time-view',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_16',
                        'label' => esc_html__( 'Display buttons share social', 'shtheme' ),
                        'name' => 'blogpost-single-sharepost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_17',
                        'label' => esc_html__( 'Display post navigation', 'shtheme' ),
                        'name' => 'blogpost-single-navipost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_18',
                        'label' => esc_html__( 'Display related post', 'shtheme' ),
                        'name' => 'blogpost-single-relatedpost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'blogpost_19',
                        'label' => esc_html__( 'Enter number post', 'shtheme' ),
                        'name' => 'blogpost-number-post-related',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'blogpost_18',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 6,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-category-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_recruitment_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'recruitment_1',
                'title' => esc_html__( 'Category Settings', 'shtheme' ),
                'fields' => array(
                    /****************** 
                    * Category 
                    ******************/
                    array(
                        'key' => 'recruitment_2',
                        'label' => esc_html__( 'Category post', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'recruitment_3',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'recruitment-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'recruitment_4',
                        'label' => esc_html__( 'Display hierarchy category', 'shtheme' ),
                        'name' => 'recruitment-hierarchy',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_5',
                        'label' => esc_html__( 'Choose category style', 'shtheme' ),
                        'name' => 'recruitment-style',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => esc_html__( 'Pagination', 'shtheme' ),
                            2 => esc_html__( 'Load more', 'shtheme' ),
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'recruitment_6',
                        'label' => esc_html__( 'Category layout', 'shtheme' ),
                        'name' => 'recruitment-layout',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'Style 1',
                            2 => 'Style 2',
                            3 => 'Style 3',
                            4 => 'Style 4',
                            5 => 'Style 5',
                        ),
                        'allow_null' => 0,
                        'default_value' => '1',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'recruitment_7',
                        'label' => esc_html__( 'Enter number post', 'shtheme' ),
                        'name' => 'recruitment-number-post',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 30,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'recruitment_8',
                        'label' => esc_html__( 'Enable Posts Thumb', 'shtheme' ),
                        'name' => 'recruitment-thumb',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_9',
                        'label' => esc_html__( 'Enable Posts Category', 'shtheme' ),
                        'name' => 'recruitment-category',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_10',
                        'label' => esc_html__( 'Enable Posts Meta', 'shtheme' ),
                        'name' => 'recruitment-meta',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_11',
                        'label' => esc_html__( 'Enable Posts Description', 'shtheme' ),
                        'name' => 'recruitment-desc',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_12',
                        'label' => esc_html__( 'Enable Posts Permalink', 'shtheme' ),
                        'name' => 'recruitment-link',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    /****************** 
                    * Single Post 
                    ******************/ 
                    array(
                        'key' => 'recruitment_13',
                        'label' => esc_html__( 'Single post', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'recruitment_14',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'recruitment-single-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'recruitment_15',
                        'label' => esc_html__( 'Display time and view post', 'shtheme' ),
                        'name' => 'recruitment-single-time-view',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_16',
                        'label' => esc_html__( 'Display buttons share social', 'shtheme' ),
                        'name' => 'recruitment-single-sharepost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_17',
                        'label' => esc_html__( 'Display post navigation', 'shtheme' ),
                        'name' => 'recruitment-single-navipost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_18',
                        'label' => esc_html__( 'Display related post', 'shtheme' ),
                        'name' => 'recruitment-single-relatedpost',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'recruitment_19',
                        'label' => esc_html__( 'Enter number post', 'shtheme' ),
                        'name' => 'recruitment-number-post-related',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'recruitment_18',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 6,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-recruitment-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_product_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'product_1',
                'title' => esc_html__( 'Product Settings', 'shtheme' ),
                'fields' => array(
                    array(
                        'key' => 'product_2',
                        'label' => esc_html__( 'Main Settings', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'product_4',
                        'label' => esc_html__( 'Enable Shop Sidebar', 'shtheme' ),
                        'name' => 'display-shopsidebar',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_5',
                        'label' => esc_html__( 'Enable Hover Flip Image Of Product', 'shtheme' ),
                        'name' => 'woo-hover-flip-image',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_6',
                        'label' => esc_html__( 'Cart', 'shtheme' ),
                        'name' => 'woocommerce-disable-cart',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    /****************** 
                    * Category Product
                    ******************/
                    array(
                        'key' => 'product_7',
                        'label' => esc_html__( 'Category Product', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'product_3',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'product-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'product_8',
                        'label' => esc_html__( 'Display hierarchy category', 'shtheme' ),
                        'name' => 'display-hierarchy-woocommerce',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_9',
                        'label' => esc_html__( 'Enter number product per page', 'shtheme' ),
                        'name' => 'number-products-cate',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 40,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'product_10',
                        'label' => esc_html__( 'Enter number product per row', 'shtheme' ),
                        'name' => 'number-column-product-cate',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'min' => 1,
                        'max' => 6,
                        'step' => 1,
                        'prepend' => '',
                        'append' => '',
                    ),
                    /****************** 
                    * Single Product 
                    ******************/ 
                    array(
                        'key' => 'product_11',
                        'label' => esc_html__( 'Single Product', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'product_12',
                        'label' => esc_html__( 'Choose Layout', 'shtheme' ),
                        'name' => 'product-single-grid',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => 'No Sidebar',
                            2 => 'Left Sidebar',
                            3 => 'Right Sidebar',
                        ),
                        'allow_null' => 0,
                        'default_value' => 2,
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'product_13',
                        'label' => esc_html__( 'Choose style of slider gallery product', 'shtheme' ),
                        'name' => 'gallery-single-style',
                        'type' => 'button_group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            1 => esc_html__( 'Horizontal', 'shtheme' ),
                            2 => esc_html__( 'Vertical', 'shtheme' ),
                        ),
                        'allow_null' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array(
                        'key' => 'product_14',
                        'label' => esc_html__( 'Enter the number of product images in the view', 'shtheme' ),
                        'name' => 'gallery-single-number-thumbnails',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 4,
                        'min' => 1,
                        'max' => 6,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'product_15',
                        'label' => esc_html__( 'Enable Zoom', 'shtheme' ),
                        'name' => 'gallery-single-zoom',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_16',
                        'label' => esc_html__( 'Enable Lightbox', 'shtheme' ),
                        'name' => 'gallery-single-lightbox',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_17',
                        'label' => esc_html__( 'Enable autoplay for gallery', 'shtheme' ),
                        'name' => 'gallery-single-autoplay',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_18',
                        'label' => esc_html__( 'Display related products', 'shtheme' ),
                        'name' => 'display-relatedpro',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'product_19',
                        'label' => esc_html__( 'Enter number related product', 'shtheme' ),
                        'name' => 'number-product-related',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'product_18',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 4,
                        'min' => 1,
                        'max' => 10,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-product-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_contact_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'contact_1',
                'title' => esc_html__( 'Contact Settings', 'shtheme' ),
                'fields' => array(
                    array(
                        'key' => 'contact_2',
                        'label' => esc_html__( 'Information contact', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'contact_3',
                        'label' => esc_html__( 'Phone', 'shtheme' ),
                        'name' => 'contact_phone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_6',
                        'label' => esc_html__( 'Email','shtheme' ),
                        'name' => 'contact_email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'contact_7',
                        'label' => esc_html__( 'Address', 'shtheme' ),
                        'name' => 'contact_address',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'contact_8',
                        'label' => esc_html__( 'Google Map', 'shtheme' ),
                        'name' => 'contact_map',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'contact_9',
                        'label' => esc_html__( 'Social', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'contact_10',
                        'label' => esc_html__( 'Facebook', 'shtheme' ),
                        'name' => 'social_facebook',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    // array(
                    //     'key' => 'contact_11',
                    //     'label' => esc_html__( 'Messenger', 'shtheme' ),
                    //     'name' => 'social_messenger',
                    //     'type' => 'text',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'default_value' => '',
                    //     'placeholder' => '',
                    //     'prepend' => '',
                    //     'append' => '',
                    //     'maxlength' => '',
                    // ),
                    array(
                        'key' => 'contact_12',
                        'label' => esc_html__( 'Youtube', 'shtheme' ),
                        'name' => 'social_youtube',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_13',
                        'label' => esc_html__( 'Instagram', 'shtheme' ),
                        'name' => 'social_instagram',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_14',
                        'label' => esc_html__( 'Tiktok', 'shtheme' ),
                        'name' => 'social_tiktok',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_15',
                        'label' => esc_html__( 'Zalo', 'shtheme' ),
                        'name' => 'social_zalo',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_16',
                        'label' => esc_html__( 'Twitter', 'shtheme' ),
                        'name' => 'social_twitter',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'contact_17',
                        'label' => esc_html__( 'Linkedin', 'shtheme' ),
                        'name' => 'social_linkedin',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-contact-settings',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
    public function add_theme_admin_field() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
                'key' => 'admin_1',
                'title' => 'Admin',
                'fields' => array(
                    array(
                        'key' => 'admin_2',
                        'label' => esc_html__( 'Restrict user', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'admin_3',
                        'label' => esc_html__( 'Restrict user', 'shtheme' ),
                        'name' => 'user-developer',
                        'type' => 'true_false',
                        'instructions' => 'Restrict user in admin page',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'admin_4',
                        'label' => esc_html__( 'Hidden information', 'shtheme' ),
                        'name' => 'btn-hidden-info',
                        'type' => 'true_false',
                        'instructions' => esc_html__( 'Hidden information dashboard & login page', 'shtheme' ),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'admin_5',
                        'label' => esc_html__( 'Insert code', 'shtheme' ),
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'admin_6',
                        'label' => esc_html__( 'Insert header', 'shtheme' ),
                        'name' => 'script-header',
                        'type' => 'textarea',
                        'instructions' => esc_html__( 'Add custom scripts inside HEAD tag. You need to have a SCRIPT tag around scripts.', 'shtheme' ),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'admin_7',
                        'label' => esc_html__( 'Insert body', 'shtheme' ),
                        'name' => 'script-body',
                        'type' => 'textarea',
                        'instructions' => esc_html__( 'Add custom scripts just after the BODY tag opened. You need to have a SCRIPT tag around scripts.', 'shtheme' ),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'admin_8',
                        'label' => esc_html__( 'Insert footer', 'shtheme' ),
                        'name' => 'script-footer',
                        'type' => 'textarea',
                        'instructions' => esc_html__( 'Add custom scripts you might want to be loaded in the footer of your website. You need to have a SCRIPT tag around scripts.', 'shtheme' ),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'theme-admin',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        endif;			
    }
}
$options = new options;